package ventanas.anadir;

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Urdaneta
 */
public class idioma extends javax.swing.JFrame {

  /**
   * Creates new form idioma
   */
  public static Font font = null;

  public idioma() {
    font = utils.cargarFuente.robotoRegular();
    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
    this.setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    volver = new javax.swing.JButton();
    anadir = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    limpiar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });
    getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

    anadir.setText("Añadir");
    anadir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        anadirActionPerformed(evt);
      }
    });
    getContentPane().add(anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

    title.setFont(font);
    title.setText("Nuevo Idioma");
    getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    jLabel2.setText("Nombre");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

    nombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreActionPerformed(evt);
      }
    });
    getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, -1));

    limpiar.setText("Limpiar");
    limpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarActionPerformed(evt);
      }
    });
    getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame idioma = new ventanas.entidades.idioma();
    this.setVisible(false);
    idioma.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
  }//GEN-LAST:event_nombreActionPerformed

  private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
    String idioma = nombre.getText().trim();

    if (idioma.isEmpty()) {
      // Notificar al usuario si dejó algún campo en blanco
      JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
      return;
    }

    utils.actualizarBase.insertar("idioma", String.format("('%s')", idioma));

    JFrame entidadesIdioma = new ventanas.entidades.idioma();
    this.setVisible(false);
    entidadesIdioma.setVisible(true);
  }//GEN-LAST:event_anadirActionPerformed

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    JFrame anadirIdioma = new ventanas.anadir.idioma();
    this.setVisible(false);
    anadirIdioma.setVisible(true);
  }//GEN-LAST:event_limpiarActionPerformed

  private void gentilicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentilicioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gentilicioActionPerformed

  private void climaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_climaActionPerformed

  private void capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_capitalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(idioma.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(idioma.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(idioma.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(idioma.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new idioma().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton anadir;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton limpiar;
  private javax.swing.JTextField nombre;
  private javax.swing.JLabel title;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
