/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.anadir;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static utils.consultarBase.consultarBase;
import utils.populateLista;

/**
 *
 * @author Juan Urdaneta
 */
public class territorio extends javax.swing.JFrame {

  /**
   * Creates new form territorio
   */
  public static Font font = null;

  class ComboItem {

    private String key;
    private String value;

    public ComboItem(String key, String value) {
      this.key = key;
      this.value = value;
    }

    @Override
    public String toString() {
      return key;
    }

    public String getKey() {
      return key;
    }

    public String getValue() {
      return value;
    }
  }

  public territorio() {
    try {
      font = utils.cargarFuente.robotoRegular();
      initComponents();
      // Center frame
      this.setLocationRelativeTo(null);
      this.setResizable(false);
      populateLista.populateSerVivo(listaSerVivo);
      populateLista.populateRelieve(listaRelieve);
      populateLista.populateIdioma(listaIdioma);
      populateLista.populateCuerpoDeAgua(listaCuerpoDeAgua);
      populateLista.populateActividadEconomica(listaActividadEconomica);

      ArrayList<String> territorios = null;
      ResultSet consulta = consultarBase("SELECT * FROM territorio;");
      capital.removeAllItems();
      capital.addItem("Seleccione");
      while (consulta.next()) {
        capital.addItem(consulta.getString("id") + " - " + new ComboItem(consulta.getString("nombre"), consulta.getString("id")).toString());
      }
    } catch (SQLException ex) {
      Logger.getLogger(territorio.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    volver = new javax.swing.JButton();
    anadir = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    ubicacion = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    superficie = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    tipo = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    capital = new javax.swing.JComboBox<String>();
    jLabel7 = new javax.swing.JLabel();
    habitantes = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listaCuerpoDeAgua = new javax.swing.JList<>();
    jLabel9 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    listaActividadEconomica = new javax.swing.JList<>();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    listaRelieve = new javax.swing.JList<>();
    jScrollPane4 = new javax.swing.JScrollPane();
    listaSerVivo = new javax.swing.JList<>();
    gentilicio = new javax.swing.JFormattedTextField();
    limpiar = new javax.swing.JButton();
    jLabel12 = new javax.swing.JLabel();
    clima = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jScrollPane6 = new javax.swing.JScrollPane();
    listaIdioma = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });

    anadir.setText("Añadir");
    anadir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        anadirActionPerformed(evt);
      }
    });

    title.setFont(font);
    title.setText("Nuevo Territorio");

    jLabel2.setText("Nombre");

    nombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreActionPerformed(evt);
      }
    });

    jLabel3.setText("Ubicación");

    ubicacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ubicacionActionPerformed(evt);
      }
    });

    jLabel4.setText("Superficie");

    jLabel5.setText("Tipo");

    jLabel6.setText("Capital");

    capital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    capital.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        capitalActionPerformed(evt);
      }
    });

    jLabel7.setText("Habitantes");

    jLabel1.setText("Gentilicio");

    jLabel8.setText("Cuerpo de Agua");

    listaCuerpoDeAgua.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(listaCuerpoDeAgua);

    jLabel9.setText("Actividad Económica");

    listaActividadEconomica.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(listaActividadEconomica);

    jLabel10.setText("Relieve");

    jLabel11.setText("Ser Vivo");

    listaRelieve.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane3.setViewportView(listaRelieve);

    listaSerVivo.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane4.setViewportView(listaSerVivo);

    gentilicio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gentilicioActionPerformed(evt);
      }
    });

    limpiar.setText("Limpiar");
    limpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarActionPerformed(evt);
      }
    });

    jLabel12.setText("Clima");

    clima.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        climaActionPerformed(evt);
      }
    });

    jLabel13.setText("Idioma");

    listaIdioma.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane6.setViewportView(listaIdioma);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel2)
              .addComponent(title)
              .addComponent(nombre)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(ubicacion)
                      .addComponent(tipo)
                      .addComponent(jLabel3)
                      .addComponent(jLabel5)
                      .addComponent(volver)
                      .addComponent(clima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(limpiar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(anadir))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel1)
                      .addComponent(habitantes))
                    .addGap(1, 1, 1))
                  .addComponent(jLabel7)
                  .addComponent(gentilicio)
                  .addComponent(superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel4))))))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 64, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel8)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10))
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(17, 17, 17))
          .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 113, Short.MAX_VALUE))
              .addComponent(capital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel13)
          .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane2)
          .addComponent(jLabel11)
          .addComponent(jScrollPane4)
          .addComponent(jScrollPane6))
        .addGap(29, 29, 29))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(title)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(superficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(habitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel12)
              .addComponent(jLabel1)
              .addComponent(jLabel13)
              .addComponent(jLabel6)))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel8)
              .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(clima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(gentilicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(volver)
              .addComponent(limpiar)
              .addComponent(anadir))))
        .addContainerGap(31, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame territorio = new ventanas.entidades.territorio();
    this.setVisible(false);
    territorio.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
  }//GEN-LAST:event_nombreActionPerformed

  private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ubicacionActionPerformed

  private void gentilicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentilicioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gentilicioActionPerformed

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    JFrame anadirTerritorio = new ventanas.anadir.territorio();
    this.setVisible(false);
    anadirTerritorio.setVisible(true);
  }//GEN-LAST:event_limpiarActionPerformed

  private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
    if (nombre.getText().trim().isEmpty() || superficie.getText().trim().isEmpty() || tipo.getText().trim().isEmpty() || ubicacion.getText().trim().isEmpty() || habitantes.getText().trim().isEmpty() || clima.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
    }

    String values = new String();

    if (capital.getSelectedIndex() != 0) {
      values = String.format("('%s', '%s', '%s', %s, %s, '%s', %s)",
          tipo.getText().trim(),
          nombre.getText().trim(),
          ubicacion.getText().trim(),
          Float.parseFloat(superficie.getText().trim()),
          Integer.parseInt(habitantes.getText().trim()),
          clima.getText().trim(),
          capital.getSelectedItem().toString().split(" ")[0]);
    } else {
      values = String.format("('%s', '%s', '%s', %s, %s, '%s', %s)",
          tipo.getText().trim(), nombre.getText().trim(), ubicacion.getText().trim(), Float.parseFloat(superficie.getText().trim()), Integer.parseInt(habitantes.getText().trim()), clima.getText().trim(), null
      );
    }
    utils.actualizarBase.insertar("territorio", values);

    Connection connection = null;
    Statement stmt = null;

    try {
      // Conectarse a la base de datos `proyecto_final` como usuario root
      connection = DriverManager.getConnection("jdbc:mariadb://localhost:3306/proyecto_final", "root", "");

      stmt = connection.createStatement();

      ResultSet rs = consultarBase("SELECT * FROM territorio ORDER BY id DESC LIMIT 1;");
      String territorio_creado_id = null;

      while (rs.next()) {
        territorio_creado_id = rs.getString("id");
      }

      if (!listaActividadEconomica.getSelectedValuesList().isEmpty()) {
        for (String str : listaActividadEconomica.getSelectedValuesList()) {
          str = str.trim();
          stmt.executeUpdate(String.format("INSERT INTO territorio_desarrolla_actividad_economica VALUES('%s', %s);", str.split(" ")[0], territorio_creado_id));
        }
      }

      if (!listaRelieve.getSelectedValuesList().isEmpty()) {
        for (String str : listaRelieve.getSelectedValuesList()) {
          str = str.trim();
          stmt.executeUpdate(String.format("INSERT INTO territorio_tiene_relieve VALUES(%s, '%s');", territorio_creado_id, str));
        }
      }
      if (!listaSerVivo.getSelectedValuesList().isEmpty()) {
        /*
        for (String str : listaSerVivo.getSelectedValuesList()) {
          str = str.trim();
          String[] aux = str.split(" ");
          stmt.executeUpdate(String.format("INSERT INTO territorio_tiene_ser_vivo VALUES(%s, '%s', '%s');", territorio_creado_id, aux[aux.length-1], aux[aux.length-2]));
        }
        */
      }
      if (!listaIdioma.getSelectedValuesList().isEmpty()) {
      }
      if (!listaCuerpoDeAgua.getSelectedValuesList().isEmpty()) {
      }
    } catch (SQLException ex) {
      Logger.getLogger(territorio.class.getName()).log(Level.SEVERE, null, ex);
    }
    JFrame anadirTerritorio = new ventanas.anadir.territorio();
    this.setVisible(false);
    anadirTerritorio.setVisible(true);
  }//GEN-LAST:event_anadirActionPerformed

  private void climaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_climaActionPerformed

  private void capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_capitalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(territorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(territorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(territorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(territorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new territorio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton anadir;
  private javax.swing.JComboBox<String> capital;
  private javax.swing.JTextField clima;
  private javax.swing.JFormattedTextField gentilicio;
  private javax.swing.JTextField habitantes;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JButton limpiar;
  private javax.swing.JList<String> listaActividadEconomica;
  private javax.swing.JList<String> listaCuerpoDeAgua;
  private javax.swing.JList<String> listaIdioma;
  private javax.swing.JList<String> listaRelieve;
  private javax.swing.JList<String> listaSerVivo;
  private javax.swing.JTextField nombre;
  private javax.swing.JTextField superficie;
  private javax.swing.JTextField tipo;
  private javax.swing.JLabel title;
  private javax.swing.JTextField ubicacion;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
