package ventanas;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Juan Urdaneta
 */
public class entidades extends javax.swing.JFrame {

  /**
   * Creates new form entidades
   */
  public static Font roboto = null;

  public entidades() {
    InputStream is = this.getClass().getClassLoader().getResourceAsStream("fonts/Roboto/Roboto-Regular.ttf");

    try {
      roboto = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(24.0F);
    } catch (FontFormatException | IOException ex) {
      Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
    }

    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    territorio = new javax.swing.JButton();
    cuerpoDeAgua = new javax.swing.JButton();
    serVivo = new javax.swing.JButton();
    actividadEconomica = new javax.swing.JButton();
    relieve = new javax.swing.JButton();
    simboloPatrio = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    title.setFont(roboto);
    title.setText("Entidades");

    territorio.setText("Territorio");

    cuerpoDeAgua.setText("Cuerpo de Agua");
    cuerpoDeAgua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cuerpoDeAguaActionPerformed(evt);
      }
    });

    serVivo.setText("Ser Vivo");
    serVivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        serVivoActionPerformed(evt);
      }
    });

    actividadEconomica.setText("Actividad Económica");

    relieve.setText("Relieve");

    simboloPatrio.setText("Símbolo Patrio");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(145, 145, 145)
            .addComponent(title))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(territorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cuerpoDeAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
              .addComponent(serVivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(37, 37, 37)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(relieve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(actividadEconomica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(simboloPatrio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(31, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addComponent(title)
        .addGap(30, 30, 30)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(territorio)
          .addComponent(actividadEconomica))
        .addGap(44, 44, 44)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cuerpoDeAgua)
          .addComponent(relieve))
        .addGap(42, 42, 42)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(serVivo)
          .addComponent(simboloPatrio))
        .addContainerGap(53, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void serVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serVivoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_serVivoActionPerformed

  private void cuerpoDeAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuerpoDeAguaActionPerformed
    // TODO add your handling code here:
    JFrame cuerposDeAgua = new ventanas.cuerpoDeAgua();
    this.setVisible(false);
    cuerposDeAgua.setVisible(true);
  }//GEN-LAST:event_cuerpoDeAguaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new entidades().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton actividadEconomica;
  private javax.swing.JButton cuerpoDeAgua;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton relieve;
  private javax.swing.JButton serVivo;
  private javax.swing.JButton simboloPatrio;
  private javax.swing.JButton territorio;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
