package ventanas;

import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author Juan Urdaneta
 */
public class menuEntidades extends javax.swing.JFrame {

  /**
   * Creates new form menuEntidades
   */
  public static Font font = null;

  public menuEntidades() {
    font = utils.cargarFuente.robotoRegular();

    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    territorio = new javax.swing.JButton();
    cuerpoDeAgua = new javax.swing.JButton();
    serVivo = new javax.swing.JButton();
    actividadEconomica = new javax.swing.JButton();
    relieve = new javax.swing.JButton();
    simboloPatrio = new javax.swing.JButton();
    volver = new javax.swing.JButton();
    idioma = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    title.setFont(font);
    title.setText("Entidades");

    territorio.setText("Territorio");
    territorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        territorioActionPerformed(evt);
      }
    });

    cuerpoDeAgua.setText("Cuerpo de Agua");
    cuerpoDeAgua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cuerpoDeAguaActionPerformed(evt);
      }
    });

    serVivo.setText("Ser Vivo");
    serVivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        serVivoActionPerformed(evt);
      }
    });

    actividadEconomica.setText("Actividad Económica");
    actividadEconomica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        actividadEconomicaActionPerformed(evt);
      }
    });

    relieve.setText("Relieve");
    relieve.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        relieveActionPerformed(evt);
      }
    });

    simboloPatrio.setText("Símbolo Patrio");
    simboloPatrio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        simboloPatrioActionPerformed(evt);
      }
    });

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });

    idioma.setText("Idioma");
    idioma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        idiomaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(148, 148, 148)
        .addComponent(title)
        .addContainerGap(193, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(idioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(territorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cuerpoDeAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(serVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(37, 37, 37)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(relieve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actividadEconomica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(simboloPatrio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(title)
        .addGap(49, 49, 49)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(territorio)
          .addComponent(actividadEconomica))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cuerpoDeAgua)
          .addComponent(relieve))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(serVivo)
          .addComponent(simboloPatrio))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(idioma)
          .addComponent(volver))
        .addContainerGap(55, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void serVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serVivoActionPerformed
    JFrame seresVivos = new ventanas.entidades.serVivo();
    this.setVisible(false);
    seresVivos.setVisible(true);
  }//GEN-LAST:event_serVivoActionPerformed

  private void cuerpoDeAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuerpoDeAguaActionPerformed
    JFrame cuerposDeAgua = new ventanas.entidades.cuerpoDeAgua();
    this.setVisible(false);
    cuerposDeAgua.setVisible(true);
  }//GEN-LAST:event_cuerpoDeAguaActionPerformed

  private void territorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territorioActionPerformed
    JFrame territorio = new ventanas.entidades.territorio();
    this.setVisible(false);
    territorio.setVisible(true);
  }//GEN-LAST:event_territorioActionPerformed

  private void actividadEconomicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadEconomicaActionPerformed
    JFrame actividadesEconomicas = new ventanas.entidades.actividadEconomica();
    this.setVisible(false);
    actividadesEconomicas.setVisible(true);
  }//GEN-LAST:event_actividadEconomicaActionPerformed

  private void relieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relieveActionPerformed
    JFrame relieves = new ventanas.entidades.relieve();
    this.setVisible(false);
    relieves.setVisible(true);
  }//GEN-LAST:event_relieveActionPerformed

  private void simboloPatrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simboloPatrioActionPerformed
    JFrame simbolosPatrios = new ventanas.entidades.simboloPatrio();
    this.setVisible(false);
    simbolosPatrios.setVisible(true);
  }//GEN-LAST:event_simboloPatrioActionPerformed

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame principal = new ventanas.principal();
    this.setVisible(false);
    principal.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaActionPerformed
    JFrame idioma = new ventanas.entidades.idioma();
    this.setVisible(false);
    idioma.setVisible(true);
  }//GEN-LAST:event_idiomaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(menuEntidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(menuEntidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(menuEntidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(menuEntidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new menuEntidades().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton actividadEconomica;
  private javax.swing.JButton cuerpoDeAgua;
  private javax.swing.JButton idioma;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton relieve;
  private javax.swing.JButton serVivo;
  private javax.swing.JButton simboloPatrio;
  private javax.swing.JButton territorio;
  private javax.swing.JLabel title;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
