package ventanas;

import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author Juan Urdaneta
 */
public class principal extends javax.swing.JFrame {

  /**
   * Creates new form principal
   */
  public static Font font = null;

  public principal() {
    font = utils.cargarFuente.robotoRegular();
    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
    // this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bg = new javax.swing.JPanel();
    pinkBg = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    explorar = new javax.swing.JButton();
    modificar = new javax.swing.JButton();
    whiteBg = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAutoRequestFocus(false);
    setResizable(false);

    bg.setMinimumSize(new java.awt.Dimension(400, 300));
    bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pinkBg.setBackground(new java.awt.Color(98, 0, 238));

    javax.swing.GroupLayout pinkBgLayout = new javax.swing.GroupLayout(pinkBg);
    pinkBg.setLayout(pinkBgLayout);
    pinkBgLayout.setHorizontalGroup(
      pinkBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 130, Short.MAX_VALUE)
    );
    pinkBgLayout.setVerticalGroup(
      pinkBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    bg.add(pinkBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

    title.setFont(font);
    title.setForeground(new java.awt.Color(0, 0, 0));
    title.setText("Hola Mundo!");
    bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

    explorar.setText("Explorar Territorios");
    explorar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        explorarActionPerformed(evt);
      }
    });
    bg.add(explorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

    modificar.setText("Modificar Datos");
    modificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modificarActionPerformed(evt);
      }
    });
    bg.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, 30));

    whiteBg.setBackground(new java.awt.Color(255, 255, 255));
    whiteBg.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout whiteBgLayout = new javax.swing.GroupLayout(whiteBg);
    whiteBg.setLayout(whiteBgLayout);
    whiteBgLayout.setHorizontalGroup(
      whiteBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 270, Short.MAX_VALUE)
    );
    whiteBgLayout.setVerticalGroup(
      whiteBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    bg.add(whiteBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 300));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
    JFrame menuEntidades = new ventanas.menuEntidades();
    this.setVisible(false);
    menuEntidades.setVisible(true);
  }//GEN-LAST:event_modificarActionPerformed

  private void explorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarActionPerformed
    JFrame territorio = new ventanas.explorarTerritorio();
    this.setVisible(false);
    territorio.setVisible(true);
  }//GEN-LAST:event_explorarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new principal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bg;
  private javax.swing.JButton explorar;
  private javax.swing.JButton modificar;
  private javax.swing.JPanel pinkBg;
  private javax.swing.JLabel title;
  private javax.swing.JPanel whiteBg;
  // End of variables declaration//GEN-END:variables
}
