package ventanas.editar;

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Urdaneta
 */
public class actividadEconomica extends javax.swing.JFrame {

  /**
   * Creates new form actividadEconomica
   */
  public static Font font = null;

  String id;

  public actividadEconomica(String nombreActividad) {
    this.id = nombreActividad;

    font = utils.cargarFuente.robotoRegular();
    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
    this.setResizable(false);

    nombre.setText(id);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    volver = new javax.swing.JButton();
    anadir = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    limpiar = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    descripcion = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    tipoRecurso = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });
    getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

    anadir.setText("Añadir");
    anadir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        anadirActionPerformed(evt);
      }
    });
    getContentPane().add(anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

    title.setFont(font);
    title.setText("Nueva Actividad Económica");
    getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    jLabel2.setText("Nombre");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

    nombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreActionPerformed(evt);
      }
    });
    getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, -1));

    limpiar.setText("Limpiar");
    limpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarActionPerformed(evt);
      }
    });
    getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

    jLabel3.setText("Descripción");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
    getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, -1));

    jLabel1.setText("Tipo");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
    getContentPane().add(tipoRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame actividadEconomica = new ventanas.entidades.actividadEconomica();
    this.setVisible(false);
    actividadEconomica.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
  }//GEN-LAST:event_nombreActionPerformed

  private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
    JTextField[] columnas = {nombre, tipoRecurso, descripcion};
    String[] actividadEconomica = new String[columnas.length];

    int index = 0;

    for (JTextField columna : columnas) {
      if (columna.getText().trim().isEmpty()) {
        // Notificar al usuario si dejó algún campo en blanco
        JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
        return;
      }
      actividadEconomica[index] = columna.getText().trim();
      index++;
    }

    actividadEconomica[0] = id;

    utils.actualizarBase.eliminar("actividad_economica", "nombre", actividadEconomica[0]);
    utils.actualizarBase.insertar("actividad_economica", String.format("('%s', '%s', '%s')", actividadEconomica));

    JFrame entidadesActividadEconomica = new ventanas.entidades.actividadEconomica();
    this.setVisible(false);
    entidadesActividadEconomica.setVisible(true);
  }//GEN-LAST:event_anadirActionPerformed

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    JFrame anadirActividad = new ventanas.anadir.actividadEconomica();
    this.setVisible(false);
    anadirActividad.setVisible(true);
  }//GEN-LAST:event_limpiarActionPerformed

  private void gentilicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentilicioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gentilicioActionPerformed

  private void climaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_climaActionPerformed

  private void capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_capitalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(actividadEconomica.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(actividadEconomica.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(actividadEconomica.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(actividadEconomica.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        // new actividadEconomica().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton anadir;
  private javax.swing.JTextField descripcion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton limpiar;
  private javax.swing.JTextField nombre;
  private javax.swing.JTextField tipoRecurso;
  private javax.swing.JLabel title;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
