package ventanas.editar;

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Urdaneta
 */
public class cuerpoDeAgua extends javax.swing.JFrame {

  /**
   * Creates new form cuerpoDeAgua
   */
  public static Font font = null;

  String cuerpoDeAguaNombre;

  public cuerpoDeAgua(String id) {
    this.cuerpoDeAguaNombre = id;
    font = utils.cargarFuente.robotoRegular();
    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    nombre.setText(id);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    volver = new javax.swing.JButton();
    modificar = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    ubicacion = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    area = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    profundidad = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    extension = new javax.swing.JTextField();
    limpiar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });
    getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

    modificar.setText("Modificar");
    modificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modificarActionPerformed(evt);
      }
    });
    getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

    title.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
    title.setText("Nuevo Cuerpo de Agua");
    getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    jLabel2.setText("Nombre");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

    nombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreActionPerformed(evt);
      }
    });
    getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, -1));

    jLabel3.setText("Ubicación");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

    ubicacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ubicacionActionPerformed(evt);
      }
    });
    getContentPane().add(ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

    jLabel4.setText("Área");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));
    getContentPane().add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, -1));

    jLabel5.setText("Profundidad");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
    getContentPane().add(profundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, -1));

    jLabel7.setText("Extensión");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
    getContentPane().add(extension, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, -1));

    limpiar.setText("Limpiar");
    limpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarActionPerformed(evt);
      }
    });
    getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame cuerpoDeAgua = new ventanas.entidades.cuerpoDeAgua();
    this.setVisible(false);
    cuerpoDeAgua.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
  }//GEN-LAST:event_nombreActionPerformed

  private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ubicacionActionPerformed

  private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
    JTextField[] camposDeTexto = {nombre, ubicacion, area, extension, profundidad};
    String[] camposDeTextoContenido = new String[camposDeTexto.length];

    int index = 0;

    for (JTextField campoDeTexto : camposDeTexto) {
      String campoDeTextoContenido = campoDeTexto.getText().trim();

      if (campoDeTextoContenido.isEmpty()) {
        // Notificar al usuario si dejó algún campo en blanco
        JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
        return;
      }

      camposDeTextoContenido[index] = campoDeTextoContenido;
      index++;
    }

    String cuerpoDeAgua = String.format("('%s', '%s', %s, %s, %s)", (Object[]) camposDeTextoContenido);

    utils.actualizarBase.eliminar("cuerpo_de_agua", "nombre", camposDeTextoContenido[0]);
    utils.actualizarBase.insertar("cuerpo_de_agua", cuerpoDeAgua);

    JFrame entidadesCuerpoDeAgua = new ventanas.entidades.cuerpoDeAgua();
    this.setVisible(false);
    entidadesCuerpoDeAgua.setVisible(true);
  }//GEN-LAST:event_modificarActionPerformed

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    JFrame anadirCuerpoDeAgua = new ventanas.anadir.cuerpoDeAgua();
    this.setVisible(false);
    anadirCuerpoDeAgua.setVisible(true);
  }//GEN-LAST:event_limpiarActionPerformed

  private void gentilicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentilicioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gentilicioActionPerformed

  private void climaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_climaActionPerformed

  private void capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_capitalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(cuerpoDeAgua.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(cuerpoDeAgua.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(cuerpoDeAgua.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(cuerpoDeAgua.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        // new cuerpoDeAgua().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField area;
  private javax.swing.JTextField extension;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton limpiar;
  private javax.swing.JButton modificar;
  private javax.swing.JTextField nombre;
  private javax.swing.JTextField profundidad;
  private javax.swing.JLabel title;
  private javax.swing.JTextField ubicacion;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
