package ventanas.editar;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import utils.ComboItem;
import static utils.consultarBase.consultarBase;

/**
 *
 * @author Juan Urdaneta
 */
public class simboloPatrio extends javax.swing.JFrame {

  /**
   * Creates new form simboloPatrio
   */
  public static Font font = null;

  String id;

  public simboloPatrio(String nombreSimbolo) {
    this.id = nombreSimbolo;

    font = utils.cargarFuente.robotoRegular();
    initComponents();
    // Center frame
    this.setLocationRelativeTo(null);
    this.setResizable(false);

    ResultSet territorios = consultarBase("SELECT * FROM territorio;");

    // remove default 'item 1, item2...' in capital JForm and add default one
    menuTerritorio.removeAllItems();
    menuTerritorio.addItem("Seleccione");

    try {
      while (territorios.next()) {
        menuTerritorio.addItem(territorios.getString("id") + " - " + new ComboItem(territorios.getString("nombre"), territorios.getString("tipo")));
      }
    } catch (SQLException ex) {
      Logger.getLogger(simboloPatrio.class.getName()).log(Level.SEVERE, null, ex);
    }

    try {
      territorios.close();
    } catch (SQLException ex) {
      Logger.getLogger(simboloPatrio.class.getName()).log(Level.SEVERE, null, ex);
    }

    ResultSet simbolos = consultarBase(String.format("SELECT nombre FROM simbolo_patrio WHERE id = %s;", id));

    try {
      simbolos.next();
      nombre.setText(simbolos.getString("nombre"));
    } catch (SQLException ex) {
      Logger.getLogger(simboloPatrio.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    volver = new javax.swing.JButton();
    modificar = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    limpiar = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    descripcion = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    menuTerritorio = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    volver.setText("Volver");
    volver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volverActionPerformed(evt);
      }
    });
    getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

    modificar.setText("Modificar");
    modificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modificarActionPerformed(evt);
      }
    });
    getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

    title.setFont(font);
    title.setText("Nuevo Símbolo Patrio");
    getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    limpiar.setText("Limpiar");
    limpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarActionPerformed(evt);
      }
    });
    getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

    jLabel3.setText("Descripción");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
    getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, -1));

    jLabel2.setText("Nombre");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
    getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

    menuTerritorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    getContentPane().add(menuTerritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 90, 140, -1));

    jLabel1.setText("Territorio");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    JFrame simboloPatrio = new ventanas.entidades.simboloPatrio();
    this.setVisible(false);
    simboloPatrio.setVisible(true);
  }//GEN-LAST:event_volverActionPerformed

  private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
    JTextField[] columnas = {nombre, descripcion};
    String[] simboloPatrio = new String[columnas.length + 2];
    simboloPatrio[0] = id;

    int index = 1;

    for (JTextField columna : columnas) {
      if (columna.getText().trim().isEmpty()) {
        // Notificar al usuario si dejó algún campo en blanco
        JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
        return;
      }
      simboloPatrio[index] = columna.getText().trim();
      index++;
    }

    if (menuTerritorio.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "No debe dejar campos de texto en blanco");
      return;
    }

    simboloPatrio[simboloPatrio.length - 1] = (String) menuTerritorio.getSelectedItem();
    simboloPatrio[simboloPatrio.length - 1] = simboloPatrio[simboloPatrio.length - 1].split(" ")[0];

    utils.actualizarBase.eliminar("simbolo_patrio", "id", id);
    utils.actualizarBase.insertar("simbolo_patrio_con_id", String.format("(%s, '%s', '%s', %s)", simboloPatrio));

    JFrame simbolosPatrios = new ventanas.entidades.simboloPatrio();
    this.setVisible(false);
    simbolosPatrios.setVisible(true);
  }//GEN-LAST:event_modificarActionPerformed

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    JFrame anadirRelieve = new ventanas.anadir.simboloPatrio();
    this.setVisible(false);
    anadirRelieve.setVisible(true);
  }//GEN-LAST:event_limpiarActionPerformed

  private void gentilicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentilicioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gentilicioActionPerformed

  private void climaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_climaActionPerformed

  private void capitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_capitalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(simboloPatrio.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(simboloPatrio.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(simboloPatrio.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(simboloPatrio.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        // new simboloPatrio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField descripcion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton limpiar;
  private javax.swing.JComboBox<String> menuTerritorio;
  private javax.swing.JButton modificar;
  private javax.swing.JTextField nombre;
  private javax.swing.JLabel title;
  private javax.swing.JButton volver;
  // End of variables declaration//GEN-END:variables
}
